services:
  anyconnect:
    image: codming/anyconnect:latest
    restart: unless-stopped
    volumes:
      - ./snell.conf:/etc/snell-server.conf
      - ./log:/var/log
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 18100:18100/tcp
      - 18100:18100/udp
    networks:
      - anyconnect
    environment:
      - SERVER_CERT=YOUR_SERVER
      - COOKIE=YOUR_COOKIE
      - SERVER_URL=https://vpn.exampe.com/

networks:
  anyconnect:
    external: false
    name: anyconnect
