services:
  anyconnect:
    image: codming/anyconnect:latest
    container_name: anyconnect
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    networks:
      - anyconnect
    environment:
      - SERVER_CERT=YOUR_SERVER_CERT
      - COOKIE=YOUR_COOKIE
      - SERVER_URL=https://vpn.example.com/
    command: /run-openconnect.sh
  xray: 
    image: codming/anyconnect:latest
    container_name: xray
    restart: unless-stopped
    volumes:
      - ./xray.json:/etc/xray.json
      - ./log:/var/log
    ports:
      - 18100:18100/tcp
      - 18100:18100/udp
    command: /usr/bin/xray -c /etc/xray.json
    depends_on:
      - anyconnect
    network_mode: "service:anyconnect"

networks:
  anyconnect:
    external: false
    name: anyconnect
