name: Build and Publish PStream

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Download Files
      run: |
        mv pstream/* .

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: codming/pstream:latest

    - name: Test image
      run: |
        echo "Starting container for testing..."
        docker run -d --name test-pstream -p 8080:8080 -p 1935:1935 codming/pstream:latest
        sleep 5
        echo "Checking if nginx is running properly..."
        docker ps | grep test-pstream
        docker logs test-pstream

        curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/ | grep -q "200" && echo "✅ HTTP test passed" || { echo "❌ HTTP test failed"; exit 1; }
        docker stop test-pstream
        docker rm test-pstream
